### ISSUE TITLE
Wrong logo

### ISSUE THREAD

**Issue by ronnietucker** [bhdouglass/fullcircle-app#1]
Hi!

Thanks for making the FCM app, it's certainly better than the webapp thing I did (with the help of an app generating web site).  :)

I've attached the FCM logo here if you want to use it in your app.
![fcm_logo](https://cloud.githubusercontent.com/assets/10391379/9427731/7de6b7b6-4984-11e5-9dd2-3137f5fcd090.png)

**All the best!**
_Ronnie_

**Comment by bhdouglass** [comment]
This is perfect, thank you! I couldn't find a high quality logo so I hacked one together. Just uploaded v1.1 to the store.
